const express = require("express");
const user = express.Router();

user.use((req, res, next) => {
  console.log("Users route accessed at :", Date.now());
  next();
});

user.get("/", (req, res) => {
  res.send(
    "Hello i am from route user, i am a route generated by different ways, i am using express.route() here"
  );
});

module.exports = user;
